openapi: 3.0.0
info:
  version: 1.0.0
  title: Tide API
  description: >-
    Check [Tide](http://wptide.org) audit reports for plugins and themes
  contact:
    email: technology@xwp.co
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: /api/v1
paths:
  /:
    get:
      summary: Schema summary
      description: >-
        Returns the API schema in the [OpenAPI
        v3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md)
        Specification (OAS) format.
      operationId: schema
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                type: object
  '/audit/wporg/{project_type}/{project_slug}/{version}':
    get:
      summary: Get audit info for a project
      description: Get a theme or plugin audit for a project client, slug and version.
      operationId: getAudit
      parameters:
        - in: path
          name: project_type
          description: The project type.
          required: true
          schema:
            type: string
            enum:
              - plugin
              - theme
        - in: path
          name: project_slug
          description: The taxonomy term representing the project slug.
          required: true
          schema:
            type: string
        - in: path
          name: version
          description: The project version number.
          required: true
          schema:
            type: string
        - in: query
          name: reports
          description: Whether or not we include audit reports in the response.
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - all
                - lighthouse
                - phpcs_phpcompatibilitywp
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Audit'
        404:
          description: Audit not found.
  '/report/{id}':
    get:
      summary: Get report by id.
      description: Get an audit report, e.g. lighthouse or phpcompatibilitywp for a specified report id listed in the audit info for a project.
      operationId: getReport
      parameters:
        - in: path
          name: id
          description: Report id.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        404:
          description: Audit not found.
components:
  schemas:
    Audit:
      type: object
    Report:
      type: object
