blank_issues_enabled: false
contact_links:
  - name: ":sos: WordPress Slack"
    url: "https://wordpress.slack.com/messages/C7TK8FBUJ/"
    about: "For project discussions and usage questions, please visit the WordPress Slack channel."
  - name: ":page_facing_up: Tide Documentation"
    url: "https://wptide.org"
    about: "Documentation for the Tide API and various services."
